### ISSUE TITLE
Cannot open worlds, keeps crashing at 87%

### ISSUE THREAD

**Issue by TalhaJabbarr** [Podshot/MCEdit-Unified#1006]
Every time i try to open a world with Mcedit2 it keeps creating an error at 87% saying " Unhandled Exeption" please i need help! I tried with Forge and Optifine version but they all do the same thing.

**Comment by Podshot** [comment]
This is a bug with MCEdit 2.0 which is a separate project. Please report it at the correct GitHub repository: https://github.com/mcedit/mcedit2
