### ISSUE TITLE
is mcedit suppose to look like this?

### ISSUE THREAD

**Issue by Dogeislove** [Podshot/MCEdit-Unified#1008]
![image](https://user-images.githubusercontent.com/48969373/89823075-11a0d700-db0e-11ea-85a2-195029224aff.png)
I am a bit worired.

**Comment by Podshot** [comment]
Yes, it's supposed to look like that when you start the program. Are you encountering a bug with the menu?

**Comment by Dogeislove** [comment]
sorry though. Got spooked for a sec. The gui looked really off.
