### ISSUE TITLE
MCEdit2 cannot find dynamically linked DLLs since MacOS 11 Big Sur

### ISSUE THREAD

**Issue by woyczek** [Podshot/MCEdit-Unified#1026]
MCEdit cannot find dynamically linked DLLs on MacOS Big Sur.
Duplicates: #1023
Version: Beta 2.14

[ERROR][main.py:203]:Unhandled Exception:
	('Unable to load OpenGL library', "Failed to load dynlib/dll 'OpenGL'. Most probably this dynlib/dll was not found when the application was frozen.", 'OpenGL', None)

More informations on https://github.com/Podshot/MCEdit-Unified/issues/1023

**Comment by Podshot** [comment]
This is a bug with MCEdit 2.0 which is a separate project. Please report it at the correct GitHub repository: https://github.com/mcedit/mcedit2

**Comment by woyczek** [comment]
#OhMy 🤦 
Thanks :)
