### ISSUE TITLE
AttributeError: 'PocketLeveldbWorld' object has no attribute 'worldFolder'

### ISSUE THREAD

**Issue by AwesomeRedstoner** [Podshot/MCEdit-Unified#729]
I use Minecraft PE to make redstone builds. I want to use MCEDIT to open, edit and save the worlds. Unfortunately, some 'errors' are preventing this from happening.

I can occasionally open the 'level.dat' of my minecraft PE world, but I cannot save it. It gives me the error message of:

'Error during <function saveAs at 0x089518F0>: AttributeError("PocketLeveldbWorld' object has no attribute 'worldFolder",)

If you want proof, here is an image...

![image](https://cloud.githubusercontent.com/assets/22513511/18940821/e81b6f3e-864e-11e6-8c22-f296c3912d58.png)

Also occasionally it give me the,

Error reading chunk: NBT stream too short. Asked for 4, only had 0

If you want proof, here is an image...

![image](https://cloud.githubusercontent.com/assets/22513511/18941206/63631400-8652-11e6-9e32-6e1d258b511e.png)

I can't save my worlds!

Please solve this!

BTW, I can't open this in mcedit 2, it is just a blank void world with nothing in it :(

**Comment by L3ice** [comment]
MCPE Support ist still really buggy.
The first error is new, but the second is already reported.
Refrence: #568

And mcedit 2 doesn't have mcpe support yet.

**Comment by LaChal** [comment]
Some progress has been made for PE support, and the second error shall not happen in the next release.
Concerning the first one, I can't remember, on my side to have encountered it :/

For reference: https://github.com/Khroki/MCEdit-Unified/issues/676#issuecomment-279105921

**Comment by naor2013** [comment]
Fixed for a long time on source
