### ISSUE TITLE
MCEdit 1.5.6.0 Undoing and schematics exporting issues.

### ISSUE THREAD

**Issue by Dushess** [Podshot/MCEdit-Unified#839]
Hello again.
The editor has two little, but a bit annoying bugs.
1) If you'll remove a row of some elements one by one, then will decide to restore it, undo operation can skip some elements from undoing. I mean it goes like that: deleted 18 parts, you undoing it, after restoring for example 12 of them operation jumps to 17 part, then you bring back last part. 13-16 elements are still deleted. That's not good.
2) During exporting something to structure file, render will make everithing white colored, This needs MCEdit restarting. It also makes grass texture simplified.
Upd: nothing from my modded worlds going to be saved to filename.nbt anyway. Operation succsessful only for vanilla blocks.

**Comment by Dushess** [comment]
1st issue seems to be disappeared, or i just not doing long enough undo row. Will check again someday.

**Comment by naor2013** [comment]
I'm almost certain the second issue is fixed in the next release, about the first one, I can't reproduce it...
We have pre-releases out, if you can test for both of those issues there, we'd love to help! Just a warning, those are pre-releases, so they're not too stable, which means you should have a backup of your maps before using it!
https://github.com/Podshot/MCEdit-Unified-Preview/releases
Thanks for the help :)

**Comment by Dushess** [comment]
Ok, i will post here found issues, small or important....

build 13:
-Action confirm hotkey (Enter) now doesn't work with NumEnter. (But it works for i.e. material selection before FILL command).
-MCEdit is slow in operations (serious delays during using hotkey/s).

**Comment by Podshot** [comment]
@Dushess Which hotkeys seem to be slow?

**Comment by Dushess** [comment]
Enter is affected, but i assume it related to processing, not exactly that key.

**Comment by Dushess** [comment]
Another issue with 1.5.6.0, probably fixed already, When view distance in config is 32, the real value is 8. No matter, what is max.

**Comment by Dushess** [comment]
Upd: beta1.6.0.30 - During filling procedure: all works fast, except serious delay on "Fill and replace" button press. And NumEnter still does not work.

**Comment by Dushess** [comment]
Okay, undo queue is good, nbt filetype also doesn't cause renderer fail. One minor issue still here, if modded blocks were saved in there, all blocks from nbt will spawn as air. But it's probably not desighed for them for now.
