### ISSUE TITLE
Error when hitting E, F, or R in Clone tool

### ISSUE THREAD

**Issue by allamassal** [Podshot/MCEdit-Unified#880]
When hitting E, F, or R on the Clone tool, I get this error:

Error during <function flip at 0x000000000AE20DD8>
TypeError("unhashable type: '_nbt.TAG_String'",)

It looks like just another one of those errors that is just there to annoy me and does not actually affect/prevent anything, but the console output mentions DEFS_ENTITIES_PAINTING and DEFS_ENTITIES_ITEM_FRAME. This never happened in the older versions like 1.5.3.0.
Also when this happens I sometimes get a broken schematic that will almost surely cause an error or crash if I hit Enter.

**Comment by allamassal** [comment]
I have also confirmed that the Regenerate Entity UUID thing has nothing to do with it because the error happened even without it checked.

**Comment by allamassal** [comment]
This error message is definitely entity related because it does not happen with a selection without entities.

**Comment by Podshot** [comment]
What version of MCEdit-Unified are you using?

**Comment by allamassal** [comment]
I am using 1.5.6.0. I said in the OP that this never happened in the older versions like 1.5.3.0.

**Comment by naor2013** [comment]
This was fixed with https://github.com/Podshot/MCEdit-Unified/commit/a706088d13507cec6b870add239ad51041b9eb27
