### ISSUE TITLE
Error while importing a schematic.

### ISSUE THREAD

**Issue by polyzium** [Podshot/MCEdit-Unified#886]
I wanted to migrate some parts of one dimension to another one but this error does not let me to do so.
![image](https://user-images.githubusercontent.com/22579935/34454461-1f0fa820-ed7d-11e7-9ee7-0e46bf82c7ce.png)
Steps to Reproduce: [here](https://user-images.githubusercontent.com/22579935/34454510-0edc55d8-ed7e-11e7-9ab5-f89bc7c46c6e.png)
MCEdit Version Number: 1.5.6.0
Minecraft Version Number: Modded 1.12.2, [mod list](https://clbin.com/AabrA)
Operating System Version: Antergos Linux with kernel 4.14.10-1-ck-ivybridge
Error log: [here](https://clbin.com/z7TCk)

**Comment by nicolaswurtz** [comment]
Hi, I've got the same issue, and solved it by removing all entities (when importing something at a place containing entities, it stops and display the error).
To remove entities, you can select all your world inside _mcedit_ and click on "delete entities".
Hope it'll work for you !

**Comment by Podshot** [comment]
It looks like you're using a mod that has different dimensions, did you try to import the schematic into a dimension that isn't present in vanilla?

**Comment by polyzium** [comment]
@Podshot I am trying to import a schematic into overworld dimension, the schematic was saved from a mod dimension.
@nicolaswurtz Lemme try that now

**Comment by Podshot** [comment]
Can you give us a copy of this schematic? I can't seem to reproduce the error

**Comment by polyzium** [comment]
[skyland_2017-12-30--15-55-27.schematic.zip](https://github.com/Khroki/MCEdit-Unified/files/1598151/skyland_2017-12-30--15-55-27.schematic.zip)
Also as nicolaswurtz said it can be solved by deleting entities at the place you want to import but why does this happen?

**Comment by Podshot** [comment]
It looks like you are running from source, are you using the latest commit?

**Comment by polyzium** [comment]
git version is too laggy. I use antergos so the AUR version of mcedit. It doesn't lag for some reason.

**Comment by Podshot** [comment]
Ok, that version is not maintained by us (nor did we give permission for it to be there to my knowledge), but it seems up-to-date. However, your log contains messages that have only been added into our source code recently, so I believe there's a mix of our current development source included, but with some changes left out. 

I was not able to reproduce this error with our current source, so I believe we have already fixed this. I'll continue testing for a few days before marking this issue as resolved.

**Comment by LaChal** [comment]
Just remember MCEdit is not (yet) able to support mods.
Currently, if your mods only changes game rules and not add dimensions or blocks/entities, all shall be fine.
Mods which add or modify blocks/entities can cause issues in MCEdit.

Also, I confirm we don't maintain the AUR version of MCEdit. I noticed the source link for MCEdit given in the repo give the archive from the 2017/01/23, which is obviously not the latest commit on this repo...
Note that, in the AUR version, the provided PE support is not accurate. A compiled version of the PE support is included in the installer, or buildable using https://github.com/Khroki/MCEdit-Unified/blob/master/pymclevel/setup_leveldb.py.

**Comment by Dushess** [comment]
Modded blocks also not causing problems, MCEdit handle them as is.

**Comment by EmeraldTiger64** [comment]
Hello. I need some assistance. When I try to import a schematic, I get the error seen in the picture.
![mcedit error](https://user-images.githubusercontent.com/31394546/35131423-b79cc736-fc8b-11e7-8aa7-d8cd4f7cc26c.PNG)
Here is the schematic I tried to upload. 
[Emerald Base - Christmas 2016 House.zip](https://github.com/Khroki/MCEdit-Unified/files/1645074/Emerald.Base.-.Christmas.2016.House.zip)

I am using schematics to get buildings such as this one off of a world that I can't get on to due to corruption and put them into a new world.

**Comment by Podshot** [comment]
@EmeraldTiger64 What version are you using? Is it one of our preview builds?

**Comment by EmeraldTiger64** [comment]
I am using MCEdit-Unified 1.5.6.0

**Comment by Podshot** [comment]
@EmeraldTiger64 I believe we have already fixed this issue for our next release

**Comment by naor2013** [comment]
Bug fixed for the next test-release
