### ISSUE TITLE
Opening a 1.13 snapshot world crashes mcedit.

### ISSUE THREAD

**Issue by Mario3264** [Podshot/MCEdit-Unified#888]
Title explains this issue.

**Comment by Podshot** [comment]
We currently do not support the new world format introduced in the 1.13 snapshots. We plan to start working on support for the format after our next release

**Comment by Kaleb217** [comment]
Any clue when that will be? I haven't been able to access a world in what feels like ages.

**Comment by Podshot** [comment]
@Kaleb217 We don't have a timeline for 1.13 support yet, we've been working with a moving target of Bedrock's map format and we probably won't start 1.13 support until after our next release

**Comment by Podshot** [comment]
Closing this issue for now since we now alert the user if they try to load a 1.13 format world
