### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by ph1823** [Podshot/MCEdit-Unified#895]
Hello, my mcedit as a error, i running mc edit on VM Ubuntu (beacause in winload is a so much file open) and i am this error: OSError: [Errno 12] Cannot allocate memory; I am 16Go RAM in my computer, how to resolve this error? Thank for reply !

**Comment by Podshot** [comment]
What version of MCEdit are you using? What is the full error log?

**Comment by naor2013** [comment]
Closing for now... If you want to give us more info, open the issue again with some more details
