### ISSUE TITLE
can't open world in mcedit-unified

### ISSUE THREAD

**Issue by dibbyrocker** [Podshot/MCEdit-Unified#900]
#### How to reproduce: When starting the MCEdit program, it shows an error (see first 6 lines on the left of screenshot). It still brings up the opening screen, though. When trying to open an existing (recently played and closed world), it errors out and can't continue (see right side of screenshot and remaining lines on the left side of the screenshot).  

![mcedit1](https://user-images.githubusercontent.com/36137990/35781950-acdfc4d4-09be-11e8-9b98-198392f87297.jpg)

## Read before submitting
If we are not able to reproduce the error, we may ask for you to submit a world so we can test it. Same process for schematics.
If you have included enough information for each section, please delete the above header and all the text below.

**Comment by Podshot** [comment]
Is this world a Windows 10/Bedrock edition world?

**Comment by dibbyrocker** [comment]
Excuse my lack of knowledge, but how would I find out? My son purchases
worlds through the marketplace on his Windows 10 PC while running the
Minecraft app. So I'm guessing it's the Windows 10 edition?

**Comment by Podshot** [comment]
Ok, so our current stable release (1.5.6.0) doesn't support loading of Windows 10 Edition worlds, but our next release will support loading of Windows 10 Edition worlds
