### ISSUE TITLE
Suggestion: Add Linux support

### ISSUE THREAD

**Issue by BinaryVigilante** [Podshot/MCEdit-Unified#901]
#### Description of Issue:
I can't use this because I'm running on Linux. And many others who use Linux won't be able to run this either.

#### Operating System: Linux

**Comment by Podshot** [comment]
We do have Linux support. Are you running into a certain error that you believe is caused solely by you using Linux?

**Comment by BinaryVigilante** [comment]
I think I just got confused...
I see now that I was just supposed to download the source code and run that? I didn't see the Linux installation guide on the front-page... Sorry :(

If that is the case, I'm sorry to have bothered you! Thank you very much anyway for replying that quick!

May you have a great day/night!

Kind regards!
