### ISSUE TITLE
ftputil won't install via pip

### ISSUE THREAD

**Issue by BinaryVigilante** [Podshot/MCEdit-Unified#904]
#### Description of Issue:

Hi,

I'm trying to run MCEdit on Ubuntu 16.04. So far I have come to where when I try to install via pip "ftputil", I get the following error:

 "Could not find a version that satisfies the requirement ftputil (from versions: )
 No matching distribution found for ftputil"

#### MCEdit Version:
Latest
#### Minecraft Version the world was last opened in:
Never gotten to it.
#### Operating System:
Ubuntu 16.04
#### A screenshot or full text of the error from the console:
  Could not find a version that satisfies the requirement ftputil (from versions: )
  No matching distribution found for ftputil

**Comment by Podshot** [comment]
It seems you need to use the command `sudo apt-get install python-ftputil` to install ftputil on Ubuntu. However, I commited a change that makes installing ftputil optional but also disables FTP support if it's not found. If you don't need FTP server support, pull our latest commit and you should be able to run MCEdit without ftputil if you don't want to install it.

**Comment by BinaryVigilante** [comment]
Thank you very much! I downloaded the newest commit and it worked.

Thank you for your help!

Have a great day/night!

Kind regards
