### ISSUE TITLE
[Suggestion] Add CC world format support,

### ISSUE THREAD

**Issue by Dushess** [Podshot/MCEdit-Unified#907]
that added by CubicChunks mod.
It's completely different worldgen, standard 16x16x256 chunks replaced by stackable 16x16x16 cubes. It provide much more operable area, but MCEdit have no idea, what is it.

It would be great, if the editor can manage new format. More info at https://discord.gg/kMfWg9m
CC is heavy WIP right now, but works itself, and also partially support mods.

**Comment by Podshot** [comment]
What are the advantages of supporting this format? How popular is this format? We currently only plan to support official vanilla formats, anything else will probably have to be added by somebody else and submitted as a Pull Request for review.

**Comment by Dushess** [comment]
Just notifying, currently mod in development, but it's finalizing idea of larger world since beta, all previous similar mods has poor perfomance. This one will be better, but of course for any serious decision we need to wait at least beta release. Also, this mod will be popular for everyone, who builds large areas, like cities and landscapes.
