### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by der-fruhling** [Podshot/MCEdit-Unified#912]
## Read before submitting
If we are not able to reproduce the error, we may ask for you to submit a world so we can test it. Same process for schematics.
If you have included enough information for each section, please delete the above header and all the text below.

**Comment by Podshot** [comment]
The texture pack loading system is trying to read a file within the .app file, a quick fix would be to temporarily move any resource packs that you current have to another directory, run mcedit, and then move them back when you're done

**Comment by ghost** [comment]
Podshot, where exactly do I put the texture pack?
