### ISSUE TITLE
Unable to build leveldb on Ubuntu 18.04 with libsnappy-dev installed: python setup_leveldb.py fails with error db/snappy_compressor.cc:6:10: fatal error: snappy/snappy.h: No such file or directory

### ISSUE THREAD

**Issue by juozaspo** [Podshot/MCEdit-Unified#919]
#### Description of Issue
Trying to build leveldb on Ubuntu 18.04 with `libsnappy-dev` package installed, using setup_leveldb.py on pymclevel directory fails with error `db/snappy_compressor.cc:6:10: fatal error: snappy/snappy.h: No such file or directory`. 
Searching for `snappy.h` in apt repositories shows `libsnappy-dev` in results, trying to install it shows that it's already installed. Leveldb builds fine in a schroot profile w/o libsnappy libs installed.

**Update:** This issue might be caused be leveldb upstream bug/outdated commit as the file that doesn't compile is within the directory created while running the script, cleaning directory tree using git (running `git clean -d -x -i`) doen't help much. 
**Update2:** symlinking snappy/snappy.h to snappy.h doesn't help much, fails with other error later.

<details><summary>Symlinking snappy header and rebuilding, still resulting in error</summary>

##### Symlinking snappy
```
sudo mkdir snappy
cd snappy
sudo ln -s ../snappy.h snappy.h
```
##### Error while trying to rebuild
```
g++ -pthread -DDLLX= -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -DNDEBUG table/table_test.cc out-static/db/builder.o out-static/db/c.o out-static/db/dbformat.o out-static/db/db_impl.o out-static/db/db_iter.o out-static/db/dumpfile.o out-static/db/filename.o out-static/db/log_reader.o out-static/db/log_writer.o out-static/db/memtable.o out-static/db/repair.o out-static/db/snappy_compressor.o out-static/db/table_cache.o out-static/db/version_edit.o out-static/db/version_set.o out-static/db/write_batch.o out-static/db/zlib_compressor.o out-static/db/zopfli_compressor.o out-static/db/zstd_compressor.o out-static/table/block_builder.o out-static/table/block.o out-static/table/filter_block.o out-static/table/format.o out-static/table/iterator.o out-static/table/merger.o out-static/table/table_builder.o out-static/table/table.o out-static/table/two_level_iterator.o out-static/util/arena.o out-static/util/bloom.o out-static/util/cache.o out-static/util/coding.o out-static/util/comparator.o out-static/util/crc32c.o out-static/util/env_boost.o out-static/util/env.o out-static/util/env_posix.o out-static/util/env_win.o out-static/util/env_winrt.o out-static/util/filter_policy.o out-static/util/hash.o out-static/util/histogram.o out-static/util/logging.o out-static/util/options.o out-static/util/status.o out-static/util/win_logger.o out-static/port/port_posix.o out-static/port/port_posix_sse.o out-static/util/testharness.o out-static/util/testutil.o -o out-static/table_test -lsnappy /lib/x86_64-linux-gnu/libz.so.1.2.11
table/table_test.cc: In function ‘bool leveldb::SnappyCompressionSupported()’:
table/table_test.cc:834:16: error: ‘Snappy_Compress’ is not a member of ‘leveldb::port’
   return port::Snappy_Compress(in.data(), in.size(), &out);
                ^~~~~~~~~~~~~~~
Makefile:371: recipe for target 'out-static/table_test' failed
make: *** [out-static/table_test] Error 1
```

</details>

**Update3:** Created an issue in upstream git: Mojang/leveldb-mcpe#25
**Update4:** Leveldb builds in schroot profile w/o libsnappy libs installed, ~but mcedit doesn't load, it shows error about missing leveldbpocket python library, both in host and schroot environments.~
**Update5:** Disregard above, fixed by running `git reset --hard` (error caused by accidentally deleting wrong files)
#### MCEdit Version
MCEdit-Unified v1.5.6.0, Commit bd5d10dd232c40f089cb119f2fe36785e633a642
#### Minecraft Version the world was last opened in
N/A
#### Operating System
Ubuntu Linux 18.04 (bionic) 64 Bits
#### A screenshot or full text of the error from the console
<details><summary>Full terminal output including build log with error messages included</summary>

```
juozas@xubuntu:~/MCEdit/MCEdit-Unified/pymclevel$ LC_ALL=C python setup_leveldb.py
========================================================================
Building Linux Minecraft Pocket Edition for MCEdit...
-----------------------------------------------------
Searching for the needed binaries (gcc, g++, unzip, wget|curl)...
g_name wget_curl True
All the needed binaries were found.
Downloading sources for leveldb
URL: https://codeload.github.com/Mojang/leveldb-mcpe/zip/5722a489c0fabf70f7bb36f70adc2ac70ff90377
Unpacking leveldb
Cleaning archive.
Downloading sources for zlib
URL: https://codeload.github.com/madler/zlib/zip/4a090adef8c773087ec8916ad3c2236ef560df27
Unpacking zlib
Cleaning archive.
Checking zlib.
Scanning /usr/lib/x86_64-linux-gnu/libfakeroot for libz.so.1.2.8
Scanning /usr/lib/x86_64-linux-gnu for libz.so.1.2.8
Scanning /lib/x86_64-linux-gnu for libz.so.1.2.8
Scanning /usr/lib64 for libz.so.1.2.8
Scanning /lib64 for libz.so.1.2.8
Scanning /lib for libz.so.1.2.8
Scanning /usr/lib for libz.so.1.2.8
Scanning /usr/local/lib for libz.so.1.2.8
Scanning /home/juozas/.local/lib for libz.so.1.2.8
Scanning /usr/local/lib for libz.so.1.2.8
Scanning /lib32 for libz.so.1.2.8
Scanning /usr/lib32 for libz.so.1.2.8
Scanning . for libz.so.1.2.8
Scanning /lib/i386-linux-gnu for libz.so.1.2.8
Scanning /usr/lib/i386-linux-gnu for libz.so.1.2.8
Scanning /lib32 for libz.so.1.2.8
Scanning /usr/lib32 for libz.so.1.2.8
Scanning /libx32 for libz.so.1.2.8
Scanning /usr/libx32 for libz.so.1.2.8
Scanning /usr/lib/x86_64-linux-gnu/libfakeroot for libz.so.1.2
Scanning /usr/lib/x86_64-linux-gnu for libz.so.1.2
Scanning /lib/x86_64-linux-gnu for libz.so.1.2
Scanning /usr/lib64 for libz.so.1.2
Scanning /lib64 for libz.so.1.2
Scanning /lib for libz.so.1.2
Scanning /usr/lib for libz.so.1.2
Scanning /usr/local/lib for libz.so.1.2
Scanning /home/juozas/.local/lib for libz.so.1.2
Scanning /usr/local/lib for libz.so.1.2
Scanning /lib32 for libz.so.1.2
Scanning /usr/lib32 for libz.so.1.2
Scanning . for libz.so.1.2
Scanning /lib/i386-linux-gnu for libz.so.1.2
Scanning /usr/lib/i386-linux-gnu for libz.so.1.2
Scanning /lib32 for libz.so.1.2
Scanning /usr/lib32 for libz.so.1.2
Scanning /libx32 for libz.so.1.2
Scanning /usr/libx32 for libz.so.1.2
Scanning /usr/lib/x86_64-linux-gnu/libfakeroot for libz.so.1
Scanning /usr/lib/x86_64-linux-gnu for libz.so.1
Scanning /lib/x86_64-linux-gnu for libz.so.1
('/lib/x86_64-linux-gnu/libz.so.1.2.11', True, '1.2.11')
*** WARNING: zlib was found, but its version is 1.2.11.
             You can try to build with this version, but it may fail,
             or the generated libraries may not work...
             Enter 'b' to build zlib v1.2.8 only for leveldb.
             Enter 'a' to quit now and install zlib yourself.
             Enter 'c' to continue.
Build continues with zlib v1.2.11
Building leveldb...
mkdir out-shared
mkdir out-shared/db
mkdir out-shared/port
mkdir out-shared/table
mkdir out-shared/util
mkdir -p out-shared/helpers/memenv
g++ -DDLLX= -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -DNDEBUG -fPIC -c db/builder.cc -o out-shared/db/builder.o
g++ -DDLLX= -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -DNDEBUG -fPIC -c db/c.cc -o out-shared/db/c.o
g++ -DDLLX= -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -DNDEBUG -fPIC -c db/db_impl.cc -o out-shared/db/db_impl.o
g++ -DDLLX= -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -DNDEBUG -fPIC -c db/db_iter.cc -o out-shared/db/db_iter.o
g++ -DDLLX= -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -DNDEBUG -fPIC -c db/dbformat.cc -o out-shared/db/dbformat.o
g++ -DDLLX= -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -DNDEBUG -fPIC -c db/dumpfile.cc -o out-shared/db/dumpfile.o
g++ -DDLLX= -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -DNDEBUG -fPIC -c db/filename.cc -o out-shared/db/filename.o
g++ -DDLLX= -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -DNDEBUG -fPIC -c db/log_reader.cc -o out-shared/db/log_reader.o
g++ -DDLLX= -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -DNDEBUG -fPIC -c db/log_writer.cc -o out-shared/db/log_writer.o
g++ -DDLLX= -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -DNDEBUG -fPIC -c db/memtable.cc -o out-shared/db/memtable.o
g++ -DDLLX= -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -DNDEBUG -fPIC -c db/repair.cc -o out-shared/db/repair.o
g++ -DDLLX= -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -DNDEBUG -fPIC -c db/snappy_compressor.cc -o out-shared/db/snappy_compressor.o
db/snappy_compressor.cc:6:10: fatal error: snappy/snappy.h: No such file or directory
 #include <snappy/snappy.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:414: recipe for target 'out-shared/db/snappy_compressor.o' failed
make: *** [out-shared/db/snappy_compressor.o] Error 1
PE support build failed.
juozas@xubuntu:~/MCEdit/MCEdit-Unified/pymclevel$ LC_ALL=C apt-file search snappy.h #search for snappy.h in apt repositories
libsnappy-dev: /usr/include/snappy.h
regina-normal-doc: /usr/share/doc/regina-normal-doc/docs/en/regina/python-snappy.html
thunderbird-dev: /usr/include/thunderbird/snappy/snappy.h
juozas@xubuntu:~/MCEdit/MCEdit-Unified/pymclevel$ LC_ALL=C sudo apt-get install libsnappy-dev #try to install libsnappy-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libsnappy-dev is already the newest version (1.1.7-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
juozas@xubuntu:~/MCEdit/MCEdit-Unified/pymclevel$ LC_ALL=C lsb_release -a #full distro info
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
juozas@xubuntu:~/MCEdit/MCEdit-Unified/pymclevel$ grep -ir snappy.h * #find all references to snappy.h in mcedit dir
leveldb/port/port_winrt.cc:#include <snappy/snappy.h>
leveldb/port/port_posix.h:#include <snappy.h>
leveldb/port/port_wp8.cc:#include <snappy/snappy.h>
leveldb/port/port_win.cc:	#include <snappy/snappy.h>
leveldb/db/snappy_compressor.cc:#include <snappy/snappy.h>
leveldb/build_detect_platform:      #include <snappy.h>

```

</details>

#### How to reproduce

1. Install/upgrade to ubuntu 18.04
2. Get the latest version (bd5d10dd232c40f089cb119f2fe36785e633a642) of mcedit using git
3. Install required dependencies to build leveldb using ubuntu package manager, **make sure `libsnappy-dev` is installed**
4. (optional) Run mcedit
5. Change Directory to `pymclevel` in mcedit root dir
6. (optional) run `python setup.py build_ext --inplace`
7. run `python setup_leveldb.py`
8. See an error near the end of build

**Comment by Podshot** [comment]
We'll look into it on our side, but if I were to guess, the change might have to come from Mojang's LevelDB

**Comment by LaChal** [comment]
The commit hash used to build this binary is not the latest one on Mojang's repo.  
The compilation has been tested successfully on prior versions of Ubuntu, and this failure may have several origins.

The `zlib` version installed on you system has not been tested,so, if you did not already try this: hit 'b' key when you get the warning about zlib version. This will use the downloaded zlib 1.2.8 sources the build this library specifically for MCEdit. Your installed one won't be affected.

Also, the `LC_ALL=C` definition shall not be necessary, however, you can try to set `CPATH=/the/path/to/snappy.h:$CPATH` and/or `CXXPATH=/the/path/to/snappy.h:$CXXPATH`.

If you want to use a more recent commit for Mojang and/or zlib code, use CLI options like described [here](https://github.com/Podshot/MCEdit-Unified/blob/bd5d10dd232c40f089cb119f2fe36785e633a642/pymclevel/INSTALL_LEVELDB)

Edit:  
@juozaspo Can you tell us why are you trying to rebubild the binary PE support?

**Comment by juozaspo** [comment]
@LaChal 
I'm unable to hit 'b' while building; it automatically continues to build with version 1.2.11 w/o even waiting for input. Also Holding 'b' all time while building doesn't help anything. 
I use `LC_ALL=C` in command line because otherwise most of error messages would be localized in copied build log.
Also I'm trying to build (not rebuild) PE support because prebuilt binary is not included while running mcedit from clean git source. When mcedit is running w/o library it shows this error:
```
[   ERROR][      pymclevel.leveldb.py:114]:The binary support for PE 1+ worlds could not be loaded:
[   ERROR][      pymclevel.leveldb.py:115]:/home/juozas/MCEdit/MCEdit-Unified/pymclevel/libleveldb.so: cannot open shared object file: No such file or directory
[ WARNING][ pymclevel.leveldbpocket.py:30]:Error while trying to import leveldb:
[ WARNING][ pymclevel.leveldbpocket.py:31]:Traceback (most recent call last):
[ WARNING][ pymclevel.leveldbpocket.py:31]:  File "/home/juozas/MCEdit/MCEdit-Unified/pymclevel/leveldbpocket.py", line 27, in <module>
[ WARNING][ pymclevel.leveldbpocket.py:31]:    import leveldb as leveldb_mcpe
[ WARNING][ pymclevel.leveldbpocket.py:31]:  File "/home/juozas/MCEdit/MCEdit-Unified/pymclevel/leveldb.py", line 116, in <module>
[ WARNING][ pymclevel.leveldbpocket.py:31]:    raise e
[ WARNING][ pymclevel.leveldbpocket.py:31]:OSError: /home/juozas/MCEdit/MCEdit-Unified/pymclevel/libleveldb.so: cannot open shared object file: No such file or directory
```
**Edit:** Running `CPATH=/usr/include/:$CPATH CXXPATH=/usr/include/:$CXXPATH python setup_leveldb.py` doesn't help much. It's still unable to find `snappy/snappy.h` while there's a `snappy.h` file in the dir of includes. Also the source code in mojang repo needs to be changed to fix that.

**Comment by LaChal** [comment]
Right, the `.so` file is not in the sources. The fact is to be usable, it requires symlinks, that can't be uploaded to Github.  

The fact that the build script is not waiting for you answer (a,b or c) let me think that something forces the `--silent` CLI switch, but I can't see what from the log you posted when you opened the issue :/  

Anyway, you can get the binaries using the Linux installer for the 1.5.6.0 version, or the [last testing one](https://github.com/LaChal/MCEdit-Unified-Linux-Preview/releases/tag/1.6.0.0-1521382932.7). (A bit old, but contains the libraries.)  
The installer of the test release is more advanced than the latest official release (will not install dependencies in your `$HOME/.local` directory, but in MCEdit one, avoiding user environment pollution), so, you may want to use this version of MCEdit.  
Note both installers create 'versioned' `mcedit` directories to avoid overriding other one(s). However, all MCEdit versions uses the same hidden folder in your `$HOME`, so backup this directory!

If you just want the binaries, pick one of the installers and follow these steps:
* ensure you don't download the installer in the same directory MCEdit is installed.
* Ensure the installer is executable.
* Run it.
* Exit it ASAP. (`I refuse`, first question, when displaying the disclaimer.)
* Copy all the `libleveldb.so*` stuff from the newly created `mcedit-<whatever-the-version>/pymclevel` folder to the `pymclevel` folder in you actual MCEdit install directory.  
* If you used the MCEdit v1.5.6.0 installer, you'll have only one `libleveldb.so.1.18` file, so create the `libleveldb.so` and `libleveldb.so.1` symlinks.

If you need to recompile, just force the build script to rebuild specific zlib support as described described [here](https://github.com/Podshot/MCEdit-Unified/blob/bd5d10dd232c40f089cb119f2fe36785e633a642/pymclevel/INSTALL_LEVELDB).

I'll try to reproduce the error on my side. (Need a bit of room on my machine...)

Let us know :)

**Comment by juozaspo** [comment]
Forcing to build zlib using `--force-zlib` command line parameter doesn't help much. Still same error on systems with `libsnappy-dev`, when include file is not symlinked to correct one. After symlinking, and deleting leveldb and leveldb-* directories, while rebuilding it errors while compiling, also as shown like in top post:
```
g++ -pthread -DDLLX= -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -DNDEBUG table/table_test.cc out-static/db/builder.o out-static/db/c.o out-static/db/db_impl.o out-static/db/db_iter.o out-static/db/dbformat.o out-static/db/dumpfile.o out-static/db/filename.o out-static/db/log_reader.o out-static/db/log_writer.o out-static/db/memtable.o out-static/db/repair.o out-static/db/snappy_compressor.o out-static/db/table_cache.o out-static/db/version_edit.o out-static/db/version_set.o out-static/db/write_batch.o out-static/db/zlib_compressor.o out-static/db/zopfli_compressor.o out-static/db/zstd_compressor.o out-static/table/block.o out-static/table/block_builder.o out-static/table/filter_block.o out-static/table/format.o out-static/table/iterator.o out-static/table/merger.o out-static/table/table.o out-static/table/table_builder.o out-static/table/two_level_iterator.o out-static/util/arena.o out-static/util/bloom.o out-static/util/cache.o out-static/util/coding.o out-static/util/comparator.o out-static/util/crc32c.o out-static/util/env.o out-static/util/env_boost.o out-static/util/env_posix.o out-static/util/env_win.o out-static/util/env_winrt.o out-static/util/filter_policy.o out-static/util/hash.o out-static/util/histogram.o out-static/util/logging.o out-static/util/options.o out-static/util/status.o out-static/util/win_logger.o out-static/port/port_posix.o out-static/port/port_posix_sse.o out-static/util/testharness.o out-static/util/testutil.o -o out-static/table_test -L/home/juozas/MCEdit/MCEdit-Unified/pymclevel -lz -Wl,-R/home/juozas/MCEdit/MCEdit-Unified/pymclevel -lsnappy
table/table_test.cc: In function 'bool leveldb::SnappyCompressionSupported()':
table/table_test.cc:834:16: error: 'Snappy_Compress' is not a member of 'leveldb::port'
   return port::Snappy_Compress(in.data(), in.size(), &out);
                ^~~~~~~~~~~~~~~
Makefile:372: recipe for target 'out-static/table_test' failed
make: *** [out-static/table_test] Error 1
PE support build failed.
```
The **upstream** code needs to be updated to refference to correct include then the build script must be updated to refference to a working commit. 
**Update:** Building on Ubuntu 18.04 **schroot** profile **w/o** `libsnappy*` libs installed leveldb builds, ~but mcedit crash on loading on both schroot and host with error No module named leveldbpocket~
**Update2:** Disregard that. Fixed by running `git reset --hard`, probably had accidentally deleted some files when cleaning up before rebuilding.

**Comment by LaChal** [comment]
@juozaspo If I understand well your last message, you could finally build the library, right?

**Comment by juozaspo** [comment]
I'm only able to build it while using separate **schroot** environment w/o `libsnappy-dev` installed. Still unable to do on my host system where `libsnappy-dev` is installed.

**Comment by LaChal** [comment]
That's annoying...

Just to make thing clear, you **SHALL NOT** build that as root. Not tested for now on my side. And, as you know, Linux systems permit to install almost anything for a user only.

Anyway, did you get the binaries from one of the installers as I described?
Could you make MCEdit run doing so?

**Comment by juozaspo** [comment]
@LaChal 
> Just to make thing clear, you **SHALL NOT** build that as root.

I clearly **_DO NOT_ use _root_ to build** any _binary_ for mcedit. **I'm using a _schroot_ utility.**
It **does _NOT_ require root to use it**. Called by **_current user_**, it **mounts _/home_** and **copies _current user's environment_** to the _**chroot being used**_ and **runs everything as the _same user_, not _root_**, at least in my configuration. 
From **schroot manual**:

> **schroot**  allows  the user to run a command or a login shell in a chroot environment.  If no command is specified, a login shell will be started in the user's current working directory inside the chroot.

Just to be clear **I don't use simple _chroot_ from any _root_ prompt** nor **i build anything using root** outside **schroot**. All i do is run **_schroot_**, not **_chroot_**, and use my **current user**.
```
juozas@xubuntu:~$ ls /
bin   core  etc   initrd.img      lib    lib64   lost+found  mnt  proc  run   sys  tmp  var      vmlinuz.old
boot  dev   home  initrd.img.old  lib32  libx32  media       opt  root  sbin  srv  usr  vmlinuz
juozas@xubuntu:~$ id
uid=1000(juozas) gid=1000(juozas) grupės=1000(juozas),4(adm),20(dialout),21(fax),24(cdrom),25(floppy),26(tape),27(sudo),29(audio),30(dip),44(video),46(plugdev),113(lpadmin),117(sambashare),123(scanner)
juozas@xubuntu:~$ schroot 
(chroot)juozas@xubuntu:~$ ls /
bin  boot  dev  etc  home  lib  lib64  media  mnt  none  opt  proc  root  run  sbin  sys  srv  tmp  usr  var
(chroot)juozas@xubuntu:~$ id
uid=1000(juozas) gid=1000(juozas) groups=1000(juozas),4(adm),20(dialout),21(fax),24(cdrom),25(floppy),26(tape),27(sudo),29(audio),30(dip),44(video),46(plugdev),113(lpadmin),117(sambashare),123(scanner)
(chroot)juozas@xubuntu:~$ exit
exit
juozas@xubuntu:~$ 
```

> Anyway, did you get the binaries from one of the installers as I described?

I didn't have time to check any of the installers yet, _i was at work at the time before_, posted from my mobile phone, no access to home pc. 

> Could you make MCEdit run doing so?

The binaries I built **using using _schroot_ as my current user**, with _chroot prefix_ **isolated from running system** were **accessible outside chroot** as **_/home_ directory were mounted inside it**, also owned by **my user** and were **working fine**, **MCEdit running properly**.

**Update:** Proof of not using root and built libraries working: https://www.youtube.com/watch?v=CI1N-f4GFmw (~5min long video)

**Comment by LaChal** [comment]
Nice :)

Please, take a moment to copy the binaries form an installer when you have time.
It may save you time.

**Comment by juozaspo** [comment]
Tried your **prebuilt** binaries from your installer, they're working. But I prefer the ones that are built in the same system they're used or in environment with the configuration as close to it. 
The ones in your installer are built using older gcc version and I'm not sure if distribution they're built on is fully compatible with the one I'm using. 
The binaries from your installed are stored in separate folder and I might use them only if my prebuilt ones should stop working.
```
juozas@xubuntu:~/MCEdit/MCEdit-Unified/pymclevel$ readelf -p .comment libleveldb/libleveldb.so

String dump of section '.comment':
  [     0]  GCC: (Ubuntu/Linaro 4.7.2-2ubuntu1) 4.7.2

juozas@xubuntu:~/MCEdit/MCEdit-Unified/pymclevel$ readelf -p .comment libleveldb.bak/libleveldb.so

String dump of section '.comment':
  [     0]  GCC: (Ubuntu 7.3.0-16ubuntu3) 7.3.0

```
In this comparison example your copies are stored in `libleveldb` directory while backups of mine are in `libleveldb.bak`.
**Update:** Looking online I found that Ubuntu version with gcc version 4.7.2-2ubuntu1 is quantal (12.10) while mine is bionic (18.04 LTS). Also quantal is **end of life** distribution release version according to ubuntu releases page.

**Comment by LaChal** [comment]
Right, Ubuntu 12.10 is EOL now.  
However, on a 14.04, the default gcc/g++ is 4.8, and 4.7 can still be installed.  
On 18.04, the default one is 7.3.0, and 4.8 can still be installed.  

-----
I could test the build on a fresh 18.04 and did no have any problem for compilation and tests.  
The system has been installed using the normal installation type and the third-party software and hardware support.

Then, the following packages installation has to be made (no surprises):
```
root@bar:# apt-get install gcc
root@bar:# apt-get install g++
root@bar:# apt-get install make
root@bar:# apt-get install python2.7
```
`MCEdit-Unified` has been downladed as a ZIP file from this commit: cba330eb68ab0f53571b655e961ef49c23483f90  
It was the latest one when I performed the tests on 18.04. Nothing has changed in the build and test scripts since you ran them.  

The library was built without any error using:
```
foo@bar:pymclevel$ python2.7 setup_leveldb.py
```

It was built using the default version of `gcc`, `g++` and `make` as provided by the package manager.

And successfully tested using:
```
foo@bar:pymclevel$ PYTHONPATH='..' python2.7 test_leveldb.py
```

All the 59 tests were successful.

-----

I don't know how you got 18.04 installed on your side, and I won't ask you that ;)  
All what can be asserted, regarding the information you provided (the `schroot` stuff mostly) and the tests I performed on my side, is that you have some software/configuration making the build fail when you use your default system/environment.

Regarding the compiler version, the fact is it is not so much important. The fact the library can work is the important thing.  
Moreover, we don't know what framework Mojang use to compile the stuff on their side. It may not be gcc/g++ at all...

-----

Closing this issue now, since the build process runs fine on the given OS, and you could sort out how to rebuild on your side.

**Comment by juozaspo** [comment]
_You didn't install `libsnappy-dev`_, the problem happens **only** when _`libsnappy-dev` is installed_, **read the title and _updated_ first post for more details**. 
In **`leveldb/build_detect_platform`**:
```
# Test whether Snappy library is installed
    # http://code.google.com/p/snappy/
    $CXX $CXXFLAGS -x c++ - -o $CXXOUTPUT 2>/dev/null  <<EOF
      #include <snappy.h>
      int main() {}
EOF
    if [ "$?" = 0 ]; then
        COMMON_FLAGS="$COMMON_FLAGS -DSNAPPY"
        PLATFORM_LIBS="$PLATFORM_LIBS -lsnappy"
    fi
```
in **`leveldb/build_config.mk`** line 1:

> SOURCES=db/builder.cc db/c.cc db/dbformat.cc db/db_impl.cc db/db_iter.cc db/dumpfile.cc db/filename.cc db/log_reader.cc db/log_writer.cc db/memtable.cc db/repair.cc **db/snappy_compressor.cc** db/table_cache.cc db/version_edit.cc db/version_set.cc db/write_batch.cc db/zlib_compressor.cc db/zopfli_compressor.cc db/zstd_compressor.cc table/block_builder.cc table/block.cc table/filter_block.cc table/format.cc table/iterator.cc table/merger.cc table/table_builder.cc table/table.cc table/two_level_iterator.cc util/arena.cc util/bloom.cc util/cache.cc util/coding.cc util/comparator.cc util/crc32c.cc util/env_boost.cc util/env.cc util/env_posix.cc util/env_win.cc util/env_winrt.cc util/filter_policy.cc util/hash.cc util/histogram.cc util/logging.cc util/options.cc util/status.cc util/win_logger.cc  port/port_posix.cc port/port_posix_sse.cc

In **`leveldb/db/snappy_compressor.cc`**:
Line 2: `#ifdef SNAPPY`
Line 6: `#include <snappy/snappy.h>`
Line 30: `#endif`
This means if `libsnappy-dev` is detected it attempts to include _snappy/snappy.h_ which doesn't exist in my installation nor is included in package.
When `libsnappy-dev` is installed, theres `/usr/include/snappy.h` but not `/usr/include/snappy/snappy.h`
Workaround: 
```
cd /usr/include #or other path containing snappy.h, included in the PATH environment variable
sudo mkdir snappy
cd snappy
sudo ln -s ../snappy.h snappy.h
```
The contents of `leveldb` directory is refering to commit (Mojang/leveldb-mcpe@5722a489c0fabf70f7bb36f70adc2ac70ff90377) on Mojang repository, this should be updated when it gets fixed upstream.
**Asuming `libsnappy-dev` is already installed,** _uninstall_ it to build sucessfully or use seperate build environment such as **schroot** to do the same.
Also check Mojang/leveldb-mcpe#25, since this is an **upstream** issue, this needs to be _fixed there first_ then pymclevel build script needs to be _changed_ to _adapt_ to updated **upstream** code.

**Comment by LaChal** [comment]
This library is not needed for `libleveldb` to be compiled and work.  
Also, when you read the build script documentation, you see how to use alternate sources for building the binary.  
Also, the build occurs as non-root, so linking stuff in the system directories using the build script is not an option...

**Comment by juozaspo** [comment]
The library _development package_ **were installed** when I wrote the issue. Only later I found it's **upstream** problem and related to `libleveldb-dev` not just `libleveldb`. It builds fine with `libleveldb`, it's the **development package** that's causing it when it's installed. 
By default build script uses commit on Mojang repository, that's why I created issue there.
For future reference you should refer to upstream issue and the build script should be updated when that issue gets fixed.
There's no need to change anything in build-script itself until upstream gets fixed, only change it to refer to updated commit when original code builds correctly.
