### ISSUE TITLE
Unable to open Windows 10 Edition maps

### ISSUE THREAD

**Issue by altariann** [Podshot/MCEdit-Unified#920]
#### Description of Issue:
My map won't open. Minecraft Java Edition maps are working properly but Windows 10 Edition maps are crashing MCEdit.
#### MCEdit Version:
MCEdit-Unified 1.5.6.0
#### Minecraft Version the world was last opened in:
Minecraft: Windows 10 Edition - v1.4.0
#### Operating System:
Windows 10
#### A screenshot or full text of the error from the console:
https://pastebin.com/NiAqvQ10
#### How to reproduce:
1. Ctrl+O
2. Select the map
3. Error: https://image.ibb.co/gar0Ao/ziktir.png

## Read before submitting
If we are not able to reproduce the error, we may ask for you to submit a world so we can test it. Same process for schematics.
If you have included enough information for each section, please delete the above header and all the text below.

**Comment by Dushess** [comment]
1.5.6.0 even can support Bedrock edition?

**Comment by Dushess** [comment]
888th issue here explains this, try 1.6.0.x test version.  https://github.com/Podshot/MCEdit-Unified-Preview/releases

**Comment by Podshot** [comment]
@Dushess Is right, try one or our testing releases and see if your issue is fixed. **Make sure to backup your worlds!**

**Comment by altariann** [comment]
Thank you so much! Now it works.
