### ISSUE TITLE
Can't Click into MCEdit Window on Windows 10

### ISSUE THREAD

**Issue by EmeraldTiger64** [Podshot/MCEdit-Unified#921]
#### Operating System: Windows 10 Home 64 bit
![image](https://user-images.githubusercontent.com/31394546/40314618-9f4ff726-5cde-11e8-8aa8-e41781b0e350.png)

#### How to reproduce: Trying to open MCEdit in the folder with the application.

**Comment by Dushess** [comment]
Did you change something in settings file before this happened?

**Comment by EmeraldTiger64** [comment]
No, I haven't edited the settings at all.

**Comment by EmeraldTiger64** [comment]
I even completely reinstalled it and it still won't work.

**Comment by EmeraldTiger64** [comment]
Nevermind, it shows up if I cascade the windows.

**Comment by Podshot** [comment]
Closing since the issue was resolved
