### ISSUE TITLE
1.13 + MCEdit 2.0.0-beta12 = CRASH

### ISSUE THREAD

**Issue by joelfrom08** [Podshot/MCEdit-Unified#922]
**Please help me everytime when i start MCEdit in an 1.13-pre1 world it chrashes**
+Podshot
When it fixed with an update, when does the update come?

**Please Help**

The peoples can me help too

**Comment by Podshot** [comment]
That is an error with MCEdit2, please report that issue [here](https://github.com/mcedit/mcedit2/issues)
