### ISSUE TITLE
Pasting Schematics with Command Blocks does not retain the commands

### ISSUE THREAD

**Issue by Xaviite** [Podshot/MCEdit-Unified#924]
#### Description of Issue:
Title explains. Here is the process I follow:
1) Create build with command blocks in single player (filled with commands)
2) Create schematic of area containing command blocks
3) Place schematic file in schematics folder of server
4) //schem load [schematic name]
5) //paste
The command blocks are empty

#### MCEdit Version:
Worldedit Bukkit-Official (6.1.8-SNAPSHOT;cd4729f)

#### Minecraft Version the world was last opened in:
1.12

#### Operating System:
Windows (this may be a server issue though)

#### A screenshot or full text of the error from the console:
No log for issue

#### How to reproduce:
See above

## Read before submitting
If we are not able to reproduce the error, we may ask for you to submit a world so we can test it. Same process for schematics.
If you have included enough information for each section, please delete the above header and all the text below.

**Comment by Podshot** [comment]
This seems like a WorldEdit issue, not an MCEdit issue. Please report it to the proper location.
