### ISSUE TITLE
MCEdit crashes when loading a bedrock world

### ISSUE THREAD

**Issue by Syvant** [Podshot/MCEdit-Unified#926]
#### Description of Issue: 
MCEdit crashes after loading a bedrock world. The chunks start loading, but the application crashes give or take 20 seconds later. I've loaded other bedrock saves no problem, but this single level continually crashes it. (Maybe because it's the only map I've played since the aquatic update and that has something to do with it).
#### MCEdit Version: 
1.6.0.45-testing-win64
#### Minecraft Version the world was last opened in: 
1.4.2
#### Operating System: 
Windows 10
#### A screenshot or full text of the error from the console:
https://pastebin.com/BZ7k2iEE

#### How to reproduce:
1. Ctrl+O
2. Open level.dat
3. Crash

**Comment by naor2013** [comment]
Can you send me a copy of this map? I'm not familiar with this issue and would love to investigate it!

**Comment by gentlegiantJGC** [comment]
is this still an issue? Can we have a copy of the world with the issue in

**Comment by Syvant** [comment]
Hi! Little late on the response so my apologies. However I can safely say this issue has been resolved using MCC Toolchest PE to convert the world to Java.

**Comment by gentlegiantJGC** [comment]
Glad we could help. Probably some issue with converting from Xbox 360

**Comment by MemeMachine537** [comment]
I actually have the same problem too. I didn't want to use mctoolchestpe to merge my worlds because I wanted the chunks to be placed in a location I could agree with. So if I use the old mcedit (which had that menu and all) crashes if I use that bedrock world; HECK any bedrock world in general. And if I use the latest release of mcedit, the chunks don't even load. Plz, someone help me.

**Comment by gentlegiantJGC** [comment]
This is a different issue. MCEdit does not support worlds from 1.13 onwards

**Comment by averageuserofgithub** [comment]
if you are close to be dead don't leave i lose my world because  in the new verison still don't work
