### ISSUE TITLE
MCEdit Crashes when jpeg image is imported.

### ISSUE THREAD

**Issue by sdadasds** [Podshot/MCEdit-Unified#929]
When I was trying to edit a map I was having issues so I switched the file type of my image to a jpeg and it resulted in an unexpected crash
MCEdit 2.0.0-Beta12
Minecraft 1.10.2
Mac OS X
To reproduce: Improt a .jpeg image for a map

**Comment by naor2013** [comment]
This is MCEdit-Unified's git.
MCEdit2's git is here: https://github.com/mcedit/mcedit2
