### ISSUE TITLE
bug for the creation of map

### ISSUE THREAD

**Issue by PhoenixFirst** [Podshot/MCEdit-Unified#933]
#### How to reproduce:

Hi,
When I load my map having added files *.schematics on this one, the game creates no more ground. The progress remains motionless.
![2018-07-20_23 13 43](https://user-images.githubusercontent.com/41491264/43025991-167120a4-8c74-11e8-8495-a1d6dbfd10e3.png)
![2018-07-20_23 13 49](https://user-images.githubusercontent.com/41491264/43025992-16957148-8c74-11e8-8357-11bf70b9c356.png)
![2018-07-20_23 14 04](https://user-images.githubusercontent.com/41491264/43025993-16af9d5c-8c74-11e8-877c-a7fc5b241400.png)
![2018-07-20_23 14 07](https://user-images.githubusercontent.com/41491264/43025994-16ca8432-8c74-11e8-88d1-13b134cd780c.png)

I use too 77 mods on minecraft. I tested without mod but that's same things

**Comment by gentlegiantJGC** [comment]
Hi. This repository is for MCedit Unified. It looks like this bug report is for MCedit 2 which is a totally different project with a repository [which can be found here](https://github.com/mcedit/mcedit2). Please can you post this there
