### ISSUE TITLE
Pre-Anvil/Post-.mclevel Worlds Won't Load

### ISSUE THREAD

**Issue by Dame-E-in** [Podshot/MCEdit-Unified#934]
I couldn't get any information on whether support was completely dropped for McRegion and Alpha level types, but what I do know is MCEdit doesn't even seem to attempt to load chunks. I even was able to load up the worlds with "minecraft_server.jar" files but the chunks don't load in MCEdit. The chunks will still load fine when I load up Minecraft, which means even when MCEdit creates the world, it corrupts nothing. It seems to only read .mca and .mclevel files.
The versions Infdev-Release 1.1. Namely the versions I used were Beta 1.3B, Beta 1.2_02 and the Infdev version that is accessible on the launcher.
I was using MCEdit v.1.5.6.0
My computer runs Windows 10. Although I don't think that matters for this case, it is in the guidelines.
![image](https://user-images.githubusercontent.com/20918683/43042218-cdee4f96-8d45-11e8-8b9f-b0be549748ff.png)
To reproduce this issue, load up an Infdev-Minecraft 1.1 world and no chunks will appear.

**Comment by Bigdbigd03** [comment]
I'll just use the original MCEdit for now.

**Comment by Podshot** [comment]
We can't confirm any working builds or that they'll solve your issue, but we have archive older MCEdit builds that you can download [here](https://github.com/Khroki/mcedit-old/releases/tag/0.1.7.1)
