### ISSUE TITLE
MC Edit won't load my world and crashes trying to load it

### ISSUE THREAD

**Issue by MechaDiddy** [Podshot/MCEdit-Unified#946]
MCEdit Unified bug report template. For MCEdit 2.0 bugs see here : https://github.com/mcedit/mcedit2
#### A screenshot or full text of the error from the console:
An error occurred while opening C:\Users\owner\AppData\Roaming\.minecraft\saves\Nintendo Power
'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 790, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 430, in __init__ (self is a EditorSession)
  File "mcedit2\panels\worldinfo.py", line 90, in __init__ (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 97, in updatePanel (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 115, in _updatePanel (self is a WorldInfoPanel)
TypeError: 'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)
#### How to reproduce:
simply select the world. It won't fully render the overview, and then trying to edit it results in a failure and an error message. 

## Read before submitting
If we are not able to reproduce the error, we may ask for you to submit a world so we can test it. Same process for schematics.
If you have included enough information for each section, please delete the above header and all the text below.

**Comment by gentlegiantJGC** [comment]
Read the first line of your bug report

**Comment by gentlegiantJGC** [comment]
Read the first line of your bug report

**Comment by MechaDiddy** [comment]
That doesn't help. I'm not a coder nor do I know what it means. I just want it to work the way it's supposed to, can you help or not?

**Comment by gentlegiantJGC** [comment]
MCEdit Unified bug report template. For MCEdit 2.0 bugs see here : https://github.com/mcedit/mcedit2

This is a bug for a different program. Go report it there
