### ISSUE TITLE
No blocks showing and crash 

### ISSUE THREAD

**Issue by vjtto** [Podshot/MCEdit-Unified#947]
#### A screenshot or full text of the error from the console:  
https://ibb.co/hdjDs9
https://ibb.co/eeVEzp
https://ibb.co/jc31ep
#### How to reproduce: open Mcedit and  load the world 

ps: I am now thinking that the problem is the world, when I open it in other versions of Minecraft the world resets itself, and yet, if I run it in 1.13, the world works good, apart from mcedit, which doesn't seem to see the blocks (it's all blank) and crashes 

For now, I'd prefer not to send the mc world for 'content' reasons, but won't wait if asked for further investigations.

**Comment by gentlegiantJGC** [comment]
We don't currently support 1.13. is this an issue in Minecraft worlds created in 1.12 and before?

**Comment by vjtto** [comment]
yes, this issue is valid with pretty much all versions, i have tested it

**Comment by naor2013** [comment]
The second and third images are from MCEdit2. MCEdit2 issues are not meant to be sent here. What version of MCEdit-Unified are you using to get the first error? And are you sure you get the same error from opening a 1.12 world too? A world that was never opened in 1.13?

**Comment by vjtto** [comment]
I know right about the Mc-edit2 thing, i just wanted to show you how both the two programs failed to operate on the same map. The World can be opened in 1.13 and fully works only in this version, i could once lunch the world in any other version ('once' was 2 days ago) but now it just reset whenever i try to, which means that the world returns at its original form, erasing all my actions completely, too odd to be true, and this is why i'm starting to believe that the problem is in the world itself.

**Comment by vjtto** [comment]
little update: none of my worlds seem to work on Mcedit

**Comment by gentlegiantJGC** [comment]
It does sound like an issue with 1.13 support. The world format changed a lot so a world opened in 1.13 will not be able to be opened in 1.12 or below. Anything to do with 1.13 is not currently supported by MCEdit.

**Comment by vjtto** [comment]
wow, if that's it then it's all clear, thanks
