### ISSUE TITLE
Adding blocks from mod

### ISSUE THREAD

**Issue by RossComputerGuy** [Podshot/MCEdit-Unified#951]
I would like to see some sort of way to import a Forge Mod for whatever version you'd like to use. It would make it easier for future mod development. Mod designers and people who build stuff using blocks and items from mods would have an easier time. When can we please get support for this?

**Comment by gentlegiantJGC** [comment]
The issue is noone on the development team uses that side of the program so we don't have any incentive to add it and we have been working on the more major side of the program. If you have any python programming experience you could help us add it (or you could give us help with the format)

**Comment by RossComputerGuy** [comment]
I have python experience but I don't know what would be needed to be done.
