### ISSUE TITLE
Import worlds to minecraft windows 10 version

### ISSUE THREAD

**Issue by ghost** [Podshot/MCEdit-Unified#954]
Hi, not a coder and new to mcedit. Im struggling to import a mcedit unified  created world into minecraft. Minecraft doesnt show any of the mcedit worlds Ive created and when I click on level, it comes up 2 seconds later that import world failed.

How do I do this? Im using the most recent mcedit unified to minecraft windows 10 edition

**Comment by gentlegiantJGC** [comment]
MCEdit is probably exporting the world in the Java world format which windows 10 edition doesn't know what to do with. I would suggest creating a world in windows 10 then opening it in MCEdit and modifying from there.
