### ISSUE TITLE
MCEdit won't start - ascii error?

### ISSUE THREAD

**Issue by 7GrandDadMC** [Podshot/MCEdit-Unified#957]
MCEdit Unified bug report template. For MCEdit 2.0 bugs see here : https://github.com/mcedit/mcedit2
#### A screenshot or full text of the error from the console: 
![image](https://user-images.githubusercontent.com/34505998/48140434-1ce92200-e2ec-11e8-9174-6f078d0533da.png)

**Comment by naor2013** [comment]
duplicate of  #770
