### ISSUE TITLE
"Empty World upon load"

### ISSUE THREAD

**Issue by faWeeBitArrogant** [Podshot/MCEdit-Unified#963]
Apologies, I am new to this.

What I am trying to do: Take Windows 10 saved worlds that were moved to pc via Realms (maybe 4 years old but have been edited since) and merge then with MCedit Unified.

What has happened: MCedit unified(post Anvil) will not load saves at all.
                                  MCedit unified(pre Anvil) will load the save, but it states that the world is 
                                  completely empty.

Minecraft Version the world was last opened in: 1.15? The newest version, just downloaded it on pc(windows 10 version) yesterday.
Operating System: Windows 10, 64 bit

In the text box, at the bottom:
NBTFormatError: Not an NBT file with a root TAG_Compound (file starts with "  "  (0x00000008)

If I am an idiot just ignore this.

**Comment by Dushess** [comment]
Probably just because there is no support of Win10 world type.

**Comment by faWeeBitArrogant** [comment]
Thank you for the responce Dushess

**Comment by gentlegiantJGC** [comment]
This is incorrect. From the sounds of it both worlds are Java worlds not bedrock worlds.
We do actually support Bedrock edition worlds but not in the outdated compiled build.

I don't really know what the actual issue is

**Comment by faWeeBitArrogant** [comment]
Im made both worlds on the xbox 360, and have no .mincraft folder: So not Java.

**Comment by gentlegiantJGC** [comment]
Ah ok. That might not work then
