### ISSUE TITLE
Cmd error

### ISSUE THREAD

**Issue by fx-k** [Podshot/MCEdit-Unified#965]
H:\Download\MCEdit-Unified-master>python mcedit.py
  File "mcedit.py", line 69
    print '[ ****** ] ~~~~~~~~~~ %s' % start_msg
                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('[ ****** ] ~~~~~~~~~~ %s' % start_msg)?

H:\Download\MCEdit-Unified-master>

**Comment by Podshot** [comment]
What version of python do you have installed? It seems like you've installed a version of Python 3 instead of Python 2.7

**Comment by fx-k** [comment]
Yeah，Python3 I had used.Do it needs python2.7?

**Comment by fx-k** [comment]
Now I use python 2.7.
![error1](https://user-images.githubusercontent.com/17313185/50287187-c18a8200-049c-11e9-9501-e853e29ca62f.PNG)
but it still happened

**Comment by gentlegiantJGC** [comment]
Please look through the [readme.md](https://github.com/Podshot/MCEdit-Unified/blob/master/README.md) for the project. There are a number of modules you need to install first.

**Comment by fx-k** [comment]
thanks
