### ISSUE TITLE
MCedit 1.5.6.0 failed to start

### ISSUE THREAD

**Issue by netherwort** [Podshot/MCEdit-Unified#970]
#### A screenshot or full text of the error from the console:
![mcedit scrnshot](https://user-images.githubusercontent.com/46546235/52513855-4a32be00-2bc2-11e9-824b-94e41ec9eab1.png)
#### How to reproduce: Install with installer and attempt to launch with mcedit.sh (if your going to test it, do it in stock raspbian)

**Comment by Podshot** [comment]
Can you run `pip list` in the shell and post the output of the command?

**Comment by netherwort** [comment]
here is the output of `pip list`:

pi@netherwort:~ $ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
automationhat (0.1.0)
blinker (1.3)
blinkt (0.1.2)
buttonshim (0.0.2)
Cap1xxx (0.1.3)
chardet (2.3.0)
click (6.6)
colorama (0.3.7)
cryptography (1.7.1)
drumhat (0.1.0)
enum34 (1.1.6)
envirophat (1.0.0)
ExplorerHAT (0.4.2)
Flask (0.12.1)
fourletterphat (0.1.0)
gpiozero (1.4.1)
idna (2.2)
ipaddress (1.0.17)
itsdangerous (0.24)
Jinja2 (2.8)
keyring (10.1)
keyrings.alt (1.3)
MarkupSafe (0.23)
mcpi (0.1.1)
microdotphat (0.2.1)
mote (0.0.3)
motephat (0.0.2)
numpy (1.12.1)
oauthlib (2.0.1)
pantilthat (0.0.5)
phatbeat (0.1.1)
pianohat (0.1.0)
picamera (1.13)
picraft (1.0)
piglow (1.2.4)
pigpio (1.38)
Pillow (4.0.0)
pip (9.0.1)
pyasn1 (0.1.9)
pycrypto (2.6.1)
pygame (1.9.3)
pygobject (3.22.0)
pyinotify (0.9.6)
PyJWT (1.4.2)
pyOpenSSL (16.2.0)
pyserial (3.2.1)
pyxdg (0.25)
rainbowhat (0.1.0)
requests (2.12.4)
requests-oauthlib (0.7.0)
RPi.GPIO (0.6.3)
RTIMULib (7.2.1)
scrollphat (0.0.7)
scrollphathd (1.2.1)
SecretStorage (2.3.1)
sense-emu (1.0)
sense-hat (2.2.0)
setuptools (33.1.1)
simplejson (3.10.0)
six (1.10.0)
skywriter (0.0.7)
sn3218 (1.2.7)
spidev (3.3)
touchphat (0.0.1)
twython (3.4.0)
unicornhathd (0.0.3)
urllib3 (1.19.1)
Werkzeug (0.11.15)
wheel (0.29.0)
pi@netherwort:~ $

**Comment by gentlegiantJGC** [comment]
Looks like you haven't installed the opengl library. Check the MCEdit readme.md for the packages you need. From a quick glance you have some of them but not all

**Comment by netherwort** [comment]
@gentlegiantJGC 
Where might I find the readme?

**Comment by gentlegiantJGC** [comment]
https://github.com/Podshot/MCEdit-Unified
