### ISSUE TITLE
i can't find ''structure to function'' button in Fliter

### ISSUE THREAD

**Issue by JinsX5** [Podshot/MCEdit-Unified#971]
MCEdit Unified bug report template. For MCEdit 2.0 bugs see here : https://github.com/mcedit/mcedit2
#### Description of Issue:
i can't find ''structure to function'' button in Fliter,i saw a video and we use the same version of mcedit. In the video he can import a schematic then use ''structure to function'' in Fliter to get function,finally cover to command and fixed to a  comple function command.
## Read before submitting
If we are not able to reproduce the error, we may ask for you to submit a world so we can test it. Same process for schematics.
If you have included enough information for each section, please delete the above header and all the text below.

**Comment by KingSean** [comment]
https://www.youtube.com/watch?v=-U1_S-38fS4   It is the video that i learned to use function command

**Comment by gentlegiantJGC** [comment]
If the issue is that you can't find the filter in MCEdit then it may be that you haven't actually put the filter in the filters directory. If it is a problem with the filter itself then you will need to contact the filter creator since it is nothing to do with us
