### ISSUE TITLE
changes don't appear in game

### ISSUE THREAD

**Issue by Mremenar** [Podshot/MCEdit-Unified#973]
MCEdit Unified bug report template. 
#### How to reproduce: 
1) Load the world in MCEdit; 
2) make changes (in my case, import schematic I created taken from another world on my PC); 
3) save changes;
4) exit MCEdit;
5) Open Minecraft;
6) See none of the modifications in game;
7) Close Minecraft;
8) Open MCEdit again;
9) load world again;
10) see changes there;
11) Google variations of "MCEdit changes don't appear in game;"
12) See that no one else has found a solution to this problem.

**Comment by gentlegiantJGC** [comment]
Your changes appear in MCEdit after you have loaded in game and reloaded MCEdit?

Two potential issues. Make sure that you only have the world logged out to the title screen in game and in MCEdit before opening the other. This can cause funny issues.

Make sure that you are actually editing the same world you are opening in game and not a backup/copy

**Comment by Mremenar** [comment]
Yes.  Double and triple checked.  Completely logged out of Minecraft.  Loaded both with short cut and by separately opening from our %appdata% directory at  
C:\Users\Sr and Jr\AppData\Roaming\.minecraft\saves
This is the in game world.  Changes/imports are visible in MCEdit but not in game.

**Comment by Mremenar** [comment]
![error](https://user-images.githubusercontent.com/48491179/56309373-5412f900-60fe-11e9-9169-0d75bd89c73c.png)
 I tried to drop a screen shot of the directory with the world

**Comment by Mremenar** [comment]
the first temp folder has an empty folder in it called "region" -- the 2nd temp file is completely empty

**Comment by Mremenar** [comment]
I found the problem.  The problem is that the schematics imported don't appear on the map mod even tho' they are present in the world.  Once the location is actually visited in world, they then magically appear on the map mod.
Before you close this bug, may I ask a totally separate question/issue?
Somebody created a cool schematic of a giant black dragon for Minecraft.  Importing it yields this error:
ValueError('Level file does not contain enough blocks! (size (1021428L,)) Try putting the size into the filename, e.g. server_level_128_128_64.dat',)), <traceback object at 0x00000000198CD848>)

any chance I can beg you to tell me how to fix this?  My 6 year old will be thrilled if we can import this dragon into our world.

**Comment by gentlegiantJGC** [comment]
Ah is it modded? That may cause issues but it is odd it still shows up in MCEdit

**Comment by Mremenar** [comment]
[huge-black-dragon.zip](https://github.com/Podshot/MCEdit-Unified/files/3090934/huge-black-dragon.zip)

**Comment by Mremenar** [comment]
I don't know if the schematic is modded.  I'm sorry for my ignorance.

**Comment by gentlegiantJGC** [comment]
I honestly have no idea what that error means

**Comment by Mremenar** [comment]
ok.  I was hopeful you might be able to tell me how to add the name it's looking for.
thank you
