### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by JockGamingLTD** [Podshot/MCEdit-Unified#975]
MCEdit Unified bug report template. For MCEdit 2.0 bugs see here : https://github.com/mcedit/mcedit2
## Read before submitting
If we are not able to reproduce the error, we may ask for you to submit a world so we can test it. Same process for schematics.
If you have included enough information for each section, please delete the above header and all the text below.

**Comment by JockGamingLTD** [comment]
mc edit failing to see world so i can open it please help

**Comment by Podshot** [comment]
No information provided. Please resubmit a new issue with the needed information

**Comment by JockGamingLTD** [comment]
when i go to load a world in to mc edit mcedit dose not see the world file 
![Screenshot (91)](https://user-images.githubusercontent.com/31765964/57564552-7ae2e900-73a5-11e9-833f-50abb67d2137.png)


mc edit version most up to date 
minecraft version 1 .11.1 
windows 10
