### ISSUE TITLE
mc edit failing to see world file 

### ISSUE THREAD

**Issue by JockGamingLTD** [Podshot/MCEdit-Unified#976]
MCEdit Unified bug report template. For MCEdit 2.0 bugs see here : https://github.com/mcedit/mcedit2
## Read before submitting
If we are not able to reproduce the error, we may ask for you to submit a world so we can test it. Same process for schematics.
If you have included enough information for each section, please delete the above header and all the text below.

**Comment by JockGamingLTD** [comment]
when i go to load a world in to mc edit mcedit dose not see the world file
![Screenshot (91)](https://user-images.githubusercontent.com/31765964/57564649-09a43580-73a7-11e9-8971-559bef8b01e0.png)


mc edit version most up to date
minecraft version 1 .11.1
windows 10

**Comment by gentlegiantJGC** [comment]
1.5 does not support bedrock. You will need the 1.6 beta. We have added a link to it on the website under more versions in the bottom right corner of the main page
