### ISSUE TITLE
Requests access to the Calendar, Contacts and Location Services

### ISSUE THREAD

**Issue by pl38** [Podshot/MCEdit-Unified#979]
MCEdit Unified bug report template. For MCEdit 2.0 bugs see here : https://github.com/mcedit/mcedit2
#### How to reproduce: 
Just load it up and the security on the Mac asks if the app is allowed to access Calendar, Contact and Location services - why would it need to do that?

**Comment by gentlegiantJGC** [comment]
There isn't an MCEdit Unified V1.7?  Where are you finding this?

**Comment by pl38** [comment]
my mistake v1.5.6.0 from here:

http://podshot.github.io/MCEdit-Unified/

**Comment by gentlegiantJGC** [comment]
I don't know why it is asking that but MCEdit does not support 1.13+ worlds

**Comment by pl38** [comment]
Just thought I'd give it a try, I'll leave it as the request are a worry, thanks anyway...
